\i etl/functions/CZ_END_AUDIT.sql
\i etl/functions/CZ_ERROR_HANDLER.sql
\i etl/functions/CZ_INFO_HANDLER.sql
\i etl/functions/CZ_START_AUDIT.sql
\i etl/functions/CZ_WRITE_AUDIT.sql
\i etl/functions/CZ_WRITE_ERROR.sql
\i etl/functions/CZ_WRITE_INFO.sql
\i etl/functions/I2B2_ADD_NODE.sql
\i etl/functions/I2B2_ADD_ROOT_NODE.sql
\i etl/functions/I2B2_BACKOUT_TRIAL.sql
\i etl/functions/I2B2_CREATE_CONCEPT_COUNTS.sql
\i etl/functions/I2B2_CREATE_SECURITY_FOR_TRIAL.sql
\i etl/functions/I2B2_DELETE_1_NODE.sql
\i etl/functions/I2B2_DELETE_ALL_NODES.sql
\i etl/functions/I2B2_FILL_IN_TREE.sql
\i etl/functions/I2B2_LOAD_ANNOTATION_DEAPP.sql
\i etl/functions/I2B2_LOAD_CLINICAL_DATA.sql
\i etl/functions/I2B2_LOAD_SECURITY_DATA.sql
\i etl/functions/I2B2_MOVE_STUDY.sql
\i etl/functions/I2B2_PROCESS_MRNA_DATA.sql
\i etl/functions/instr.sql
\i etl/functions/is_date.sql
\i etl/functions/is_numeric.sql
\i etl/functions/median.sql
\i etl/functions/PARSE_NTH_VALUE.sql
--\i etl/functions/transmartApp-DB_Post.sql