CREATE ROLE i2b2demodata LOGIN
  PASSWORD 'i2b2demodata'
  SUPERUSER INHERIT CREATEDB NOCREATEROLE NOREPLICATION;

CREATE ROLE i2b2metadata LOGIN
  PASSWORD 'i2b2metadata'
  SUPERUSER INHERIT CREATEDB NOCREATEROLE NOREPLICATION;

CREATE ROLE i2b2hive LOGIN
  PASSWORD 'i2b2hive'
  SUPERUSER INHERIT CREATEDB NOCREATEROLE NOREPLICATION;

CREATE ROLE i2b2pm LOGIN
  PASSWORD 'i2b2pm'
  SUPERUSER INHERIT CREATEDB NOCREATEROLE NOREPLICATION;

CREATE ROLE i2b2workdata LOGIN
  PASSWORD 'i2b2workdata'
  SUPERUSER INHERIT CREATEDB NOCREATEROLE NOREPLICATION;

CREATE SCHEMA i2b2demodata AUTHORIZATION i2b2demodata;
CREATE SCHEMA i2b2metadata AUTHORIZATION i2b2metadata;
CREATE SCHEMA i2b2hive AUTHORIZATION i2b2hive;
CREATE SCHEMA i2b2pm AUTHORIZATION i2b2pm;
CREATE SCHEMA i2b2workdata AUTHORIZATION i2b2workdata;


ALTER ROLE i2b2demodata IN DATABASE transmart SET search_path=i2b2demodata,public;
ALTER ROLE i2b2metadata IN DATABASE transmart SET search_path=i2b2metadata,public;
ALTER ROLE i2b2hive IN DATABASE transmart SET search_path=i2b2hive,public;
ALTER ROLE i2b2pm IN DATABASE transmart SET search_path=i2b2pm,public;
ALTER ROLE i2b2workdata IN DATABASE transmart SET search_path=i2b2workdata,public;