CREATE TABLE I2B2DEMODATA.NEWS_UPDATES
(
NEWSID       integer ,
RANBYUSER    VARCHAR(200 ) ,
ROWSAFFECTED integer ,
OPERATION    VARCHAR(200 ) ,
DATASETNAME  VARCHAR(200 ) ,
UPDATEDATE TIMESTAMP(6) ,
COMMENTFIELD VARCHAR(200 )
);

CREATE TABLE I2B2METADATA.I2B2_TAGS
(
TAG_ID   integer NOT NULL ,
PATH     VARCHAR(400 ) ,
TAG      VARCHAR(400 ) ,
TAG_TYPE VARCHAR(400 ) ,
TAGS_IDX integer NOT NULL
);

CREATE TABLE I2B2DEMODATA.ASYNC_JOB
(
ID         	integer,
JOB_NAME   	VARCHAR(200 ),
JOB_STATUS 	VARCHAR(200 ),
RUN_TIME   	VARCHAR(200 ),
LAST_RUN_ON 	TIMESTAMP (6),
VIEWER_URL     	VARCHAR(4000 ),
ALT_VIEWER_URL 	VARCHAR(600 ),
JOB_RESULTS 	text,
JOB_TYPE 	VARCHAR(20 )
);

