\set ON_ERROR_STOP ON

DROP TABLE tm_lz.lt_src_study_metadata;
CREATE TABLE tm_lz.lt_src_study_metadata
  (
    STUDY_OWNER             varchar(510),
    STUDY_PHASE             varchar(100),
    STUDY_ID                varchar(100),
    DESIGN                  varchar(2000),
    OVERALL_DESIGN          varchar(2000),
    CONTACT_FIELD           varchar(400),
    INSTITUTION             varchar(100),
    DURATION_OF_STUDY_WEEKS varchar(200),
    ACCESS_TYPE             varchar(100),
    TYPE_OF_CONTROL         varchar(510),
    NUMBER_OF_SITES         varchar(200),
    MAX_AGE                 varchar(100),
    SECONDARY_IDS           varchar(510),
    STATUS                  varchar(100),
    BLINDING_PROCEDURE      varchar(1000),
    SUBJECTS                varchar(2000),
    GENDER_RESTRICTION_MFB  varchar(510),
    MIN_AGE                 varchar(100),
    SEARCH_AREA             varchar(100),
    DOSING_REGIMEN          varchar(3500),
    TARGET                  varchar(255),
    PRIMARY_END_POINTS      varchar(2000),
    NUMBER_OF_PATIENTS      varchar(200),
    GROUP_ASSIGNMENT        varchar(510),
    STUDYTYPE               varchar(510),
    DISEASE                 varchar(1000),
    ROUTE_OF_ADMINISTRATION varchar(510),
    BIOMARKER_TYPE          varchar(255),
    COMPOUND                varchar(1000),
    EXCLUSION_CRITERIA      varchar(4000),
    SECONDARY_END_POINTS    varchar(3500),
    DESCRIPTION 			varchar(2000),
    ORGANISM             varchar(200),
    COUNTRY              varchar(50),
    MAIN_FINDINGS        varchar(2000),
    GEO_PLATFORM         varchar(100),
    DEVELOPMENT_PARTNER  varchar(100),
    START_DATE           varchar(50),
    COMPLETION_DATE      varchar(50),
    PRIMARY_INVESTIGATOR varchar(400),
    INCLUSION_CRITERIA   varchar(4000),
    TITLE                varchar(1000),
    PUBMED_IDS           varchar(1000)
 );
  ALTER TABLE tm_lz.lt_src_study_metadata OWNER TO tm_lz;