LOAD DATA
INFILE 'load_variant_subject_summary.txt'
   INTO TABLE DE_VARIANT_SUBJECT_SUMMARY
   FIELDS TERMINATED BY X'9'
   TRAILING NULLCOLS
   (
    CHR,
    POS,
    DATASET_ID,
    SUBJECT_ID,
    RS_ID,
    VARIANT,
    VARIANT_FORMAT,
    VARIANT_TYPE,
    VARIANT_SUBJECT_SUMMARY_ID  "DE_VARIANT_SUBJECT_SUMMARY_SEQ.nextval"
    )


