--------------------------------------------------------
--  File created - Thursday-April-11-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DE_VARIANT_DATASET
--------------------------------------------------------

  CREATE TABLE "DEAPP"."DE_VARIANT_DATASET" 
   (	"DATASET_ID" VARCHAR2(50 BYTE), 
	"DATASOURCE_ID" VARCHAR2(200 BYTE), 
	"ETL_ID" VARCHAR2(20 BYTE), 
	"ETL_DATE" DATE, 
	"GENOME" VARCHAR2(50 BYTE), 
	"METADATA_COMMENT" CLOB, 
	"VARIANT_DATASET_TYPE" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DEAPP" 
 LOB ("METADATA_COMMENT") STORE AS BASICFILE (
  TABLESPACE "DEAPP" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table DE_VARIANT_SUBJECT_DETAIL
--------------------------------------------------------

  CREATE TABLE "DEAPP"."DE_VARIANT_SUBJECT_DETAIL" 
   (	"VARIANT_SUBJECT_DETAIL_ID" NUMBER(9,0), 
	"DATASET_ID" VARCHAR2(50 BYTE), 
	"CHR" VARCHAR2(50 BYTE), 
	"POS" NUMBER(20,0), 
	"RS_ID" VARCHAR2(50 BYTE), 
	"REF" VARCHAR2(100 BYTE), 
	"ALT" VARCHAR2(100 BYTE), 
	"QUAL" VARCHAR2(100 BYTE), 
	"FILTER" VARCHAR2(50 BYTE), 
	"INFO" VARCHAR2(2000 BYTE), 
	"FORMAT" VARCHAR2(50 BYTE), 
	"VARIANT_VALUE" CLOB
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DEAPP" 
 LOB ("VARIANT_VALUE") STORE AS BASICFILE (
  TABLESPACE "DEAPP" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) 
  CACHE ;
--------------------------------------------------------
--  DDL for Table DE_VARIANT_SUBJECT_IDX
--------------------------------------------------------

  CREATE TABLE "DEAPP"."DE_VARIANT_SUBJECT_IDX" 
   (	"DATASET_ID" VARCHAR2(50 BYTE), 
	"SUBJECT_ID" VARCHAR2(50 BYTE), 
	"POSITION" NUMBER(10,0), 
	"VARIANT_SUBJECT_IDX_ID" NUMBER(18,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DEAPP" ;
--------------------------------------------------------
--  DDL for Table DE_VARIANT_SUBJECT_SUMMARY
--------------------------------------------------------

  CREATE TABLE "DEAPP"."DE_VARIANT_SUBJECT_SUMMARY" 
   (	"VARIANT_SUBJECT_SUMMARY_ID" NUMBER(9,0), 
	"CHR" VARCHAR2(50 BYTE), 
	"POS" NUMBER(20,0), 
	"DATASET_ID" VARCHAR2(50 BYTE), 
	"SUBJECT_ID" VARCHAR2(50 BYTE), 
	"RS_ID" VARCHAR2(50 BYTE), 
	"VARIANT" VARCHAR2(100 BYTE), 
	"VARIANT_FORMAT" VARCHAR2(100 BYTE), 
	"VARIANT_TYPE" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DEAPP" ;
--------------------------------------------------------
--  DDL for Index SYS_C0035476
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEAPP"."SYS_C0035476" ON "DEAPP"."DE_VARIANT_DATASET" ("DATASET_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DEAPP" ;
--------------------------------------------------------
--  DDL for Index DE_VARIANT_SUB_DT_IDX1
--------------------------------------------------------

  CREATE INDEX "DEAPP"."DE_VARIANT_SUB_DT_IDX1" ON "DEAPP"."DE_VARIANT_SUBJECT_DETAIL" ("DATASET_ID", "RS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DE_VARIANT_SUB_DETAIL_IDX2
--------------------------------------------------------

  CREATE INDEX "DEAPP"."DE_VARIANT_SUB_DETAIL_IDX2" ON "DEAPP"."DE_VARIANT_SUBJECT_DETAIL" ("DATASET_ID", "CHR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0035487
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEAPP"."SYS_C0035487" ON "DEAPP"."DE_VARIANT_SUBJECT_DETAIL" ("VARIANT_SUBJECT_DETAIL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DEAPP" ;
--------------------------------------------------------
--  DDL for Index VARIANT_SUBJECT_DETAIL_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEAPP"."VARIANT_SUBJECT_DETAIL_UK" ON "DEAPP"."DE_VARIANT_SUBJECT_DETAIL" ("DATASET_ID", "CHR", "POS", "RS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DEAPP" ;
--------------------------------------------------------
--  DDL for Index VARIANT_SUBJECT_IDX_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEAPP"."VARIANT_SUBJECT_IDX_UK" ON "DEAPP"."DE_VARIANT_SUBJECT_IDX" ("DATASET_ID", "SUBJECT_ID", "POSITION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DEAPP" ;
--------------------------------------------------------
--  DDL for Index SYS_C0035492
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEAPP"."SYS_C0035492" ON "DEAPP"."DE_VARIANT_SUBJECT_SUMMARY" ("VARIANT_SUBJECT_SUMMARY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DEAPP" ;
--------------------------------------------------------
--  DDL for Index VARIANT_SUBJECT_SUMMARY_UK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEAPP"."VARIANT_SUBJECT_SUMMARY_UK" ON "DEAPP"."DE_VARIANT_SUBJECT_SUMMARY" ("DATASET_ID", "CHR", "POS", "RS_ID", "SUBJECT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DEAPP" ;
--------------------------------------------------------
--  Constraints for Table DE_VARIANT_DATASET
--------------------------------------------------------

  ALTER TABLE "DEAPP"."DE_VARIANT_DATASET" MODIFY ("GENOME" NOT NULL ENABLE);
 
  ALTER TABLE "DEAPP"."DE_VARIANT_DATASET" ADD PRIMARY KEY ("DATASET_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DEAPP"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DE_VARIANT_SUBJECT_DETAIL
--------------------------------------------------------

  ALTER TABLE "DEAPP"."DE_VARIANT_SUBJECT_DETAIL" ADD PRIMARY KEY ("VARIANT_SUBJECT_DETAIL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DEAPP"  ENABLE;
 
  ALTER TABLE "DEAPP"."DE_VARIANT_SUBJECT_DETAIL" ADD CONSTRAINT "VARIANT_SUBJECT_DETAIL_UK" UNIQUE ("DATASET_ID", "CHR", "POS", "RS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DEAPP"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DE_VARIANT_SUBJECT_IDX
--------------------------------------------------------

  ALTER TABLE "DEAPP"."DE_VARIANT_SUBJECT_IDX" ADD CONSTRAINT "VARIANT_SUBJECT_IDX_UK" UNIQUE ("DATASET_ID", "SUBJECT_ID", "POSITION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DEAPP"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DE_VARIANT_SUBJECT_SUMMARY
--------------------------------------------------------

  ALTER TABLE "DEAPP"."DE_VARIANT_SUBJECT_SUMMARY" MODIFY ("DATASET_ID" NOT NULL ENABLE);
 
  ALTER TABLE "DEAPP"."DE_VARIANT_SUBJECT_SUMMARY" MODIFY ("SUBJECT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "DEAPP"."DE_VARIANT_SUBJECT_SUMMARY" ADD PRIMARY KEY ("VARIANT_SUBJECT_SUMMARY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DEAPP"  ENABLE;
 
  ALTER TABLE "DEAPP"."DE_VARIANT_SUBJECT_SUMMARY" ADD CONSTRAINT "VARIANT_SUBJECT_SUMMARY_UK" UNIQUE ("DATASET_ID", "CHR", "POS", "RS_ID", "SUBJECT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "DEAPP"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DE_VARIANT_SUBJECT_DETAIL
--------------------------------------------------------

  ALTER TABLE "DEAPP"."DE_VARIANT_SUBJECT_DETAIL" ADD CONSTRAINT "VARIANT_SUBJECT_DETAIL_FK" FOREIGN KEY ("DATASET_ID")
	  REFERENCES "DEAPP"."DE_VARIANT_DATASET" ("DATASET_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DE_VARIANT_SUBJECT_IDX
--------------------------------------------------------

  ALTER TABLE "DEAPP"."DE_VARIANT_SUBJECT_IDX" ADD CONSTRAINT "VARIANT_SUBJECT_IDX_FK" FOREIGN KEY ("DATASET_ID")
	  REFERENCES "DEAPP"."DE_VARIANT_DATASET" ("DATASET_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DE_VARIANT_SUBJECT_SUMMARY
--------------------------------------------------------

  ALTER TABLE "DEAPP"."DE_VARIANT_SUBJECT_SUMMARY" ADD CONSTRAINT "VARIANT_SUBJECT_SUMMARY_FK" FOREIGN KEY ("DATASET_ID")
	  REFERENCES "DEAPP"."DE_VARIANT_DATASET" ("DATASET_ID") ENABLE;
