CREATE TABLE I2B2DEMODATA.NEWS_UPDATES
(
NEWSID       integer ,
RANBYUSER    VARCHAR(200 ) ,
ROWSAFFECTED integer ,
OPERATION    VARCHAR(200 ) ,
DATASETNAME  VARCHAR(200 ) ,
UPDATEDATE TIMESTAMP(6) ,
COMMENTFIELD VARCHAR(200 )
);

CREATE TABLE I2B2METADATA.I2B2_TAGS
(
TAG_ID   integer NOT NULL ,
PATH     VARCHAR(400 ) ,
TAG      VARCHAR(400 ) ,
TAG_TYPE VARCHAR(400 ) ,
TAGS_IDX integer NOT NULL
);

